return {
    timeline_motion = {
        ["0"] = "ProjectStart",
        ["<C-$>"] = "ProjectEnd",
        ["f"] = "PlayPosition",
        ["x"] = "MousePosition",
        ["["] = "LoopStart",
        ["]"] = "LoopEnd",
        ["<left>"] = "PrevMarker",
        ["<right>"] = "NextMarker",
        ["<M-left>"] = "PrevTimeSignatureMarker",
        ["<M-right>"] = "NextTimeSignatureMarker",
        ["<M-h>"] = "Left10Pix",
        ["<M-l>"] = "Right10Pix",
        ["<M-H>"] = "Left40Pix",
        ["<M-L>"] = "Right40Pix",
        ["h"] = "LeftGridDivision",
        ["l"] = "RightGridDivision",
        ["H"] = "PrevMeasure",
        ["L"] = "NextMeasure",
        ["<C-i>"] = "MoveRedo",
        ["<C-o>"] = "MoveUndo",
        ["<C-h>"] = "Prev4Beats",
        ["<C-l>"] = "Next4Beats",
        ["<C-H>"] = "Prev4Measures",
        ["<C-L>"] = "Next4Measures",
        ["`"] = "MarkedTimelinePosition",
    },
    timeline_operator = {
        ["r"] = "Record",
        ["<C-p>"] = "DuplicateTimeline",
        ["t"] = "PlayAndLoop",
        ["|"] = "CreateMeasures",
        ["<C-|>"] = "CreateProjectTempo"
    },
    timeline_selector = {
        ["~"] = "MarkedRegion",
        ["!"] = "LoopSelection",
        ["<S-right>"] = "NextRegion",
        ["<S-left>"] = "PrevRegion",
        ["<CS-right>"] = "TimeSelectionShiftedRight",
        ["<CS-left>"] = "TimeSelectionShiftedLeft",
        ["i"] = {"+inner", {
            ["<M-w>"] = "AutomationItem",
            ["l"] = "AllTrackItems",
            ["r"] = "Region",
            ["p"] = "ProjectTimeline",
            ["w"] = "Item",
            ["W"] = "BigItem",
        }},
    },
    visual_timeline_command = {
        ["v"] = "SetModeNormal",
        ["o"] = "SwitchTimelineSelectionSide",
    },
    command = {
        ["."] = "RepeatLastCommand",
        ["@"] = "PlayMacro",
        [","] = "RecordMacro",
        ["<ESC>"] = "Reset",
        ["<C-m>"] = "ToggleViewMixer",
        ["<C-v>"] = "ToggleVideoWindow",
        ["<backspace>"] = "RemoveTimeSelection",
        ["<C-SPC>"] = "PlayStop",
        ["<C-r>"] = "Redo",
        ["u"] = "Undo",
        ["v"] = "SetModeVisualTimeline",

        ["<C-s>"] = "SelectItemsUnderEditCursor",
        ["x"] = "ToggleLoop",
        ["m"] = "ToggleMute",
        ["s"] = "ToggleSolo",
        ["x"] = "ZoomUndo",
        [""] = "NextRegion",
        [""] = "PrevRegion",

        ["z"] = { "+zoom", {
            ["t"] = "ToggleSmartZoom",
            ["z"] = "ScrollToSelectedTracks",
            ["d"] = "LoadZoomPreset1",
            ["g"] = "ZoomProject",
        }},

        ["<SPC>"] = { "+leader commands", {
            ["<SPC>"] = "ShowActionList",

            ["r"] = { "+render", {
                ["m"] = "RenderTrackMono",
                ["t"] = "RenderItemsToNewTake",
                ["p"] = "RenderProjectWithLastSetting",
                ["P"] = "RenderProject",
                ["s"] = "RenderTrack",
            }},

            ["R"] = { "+REAPER", {
                ["p"] = "PackageManagerBrowse",
                ["o"] = "ShowPreferences",
            }},

            ["m"] = { "+markers", {
                ["l"] = "OpenMarkerList",
                ["m"] = "InsertOrEditMarker",
                ["M"] = "Mark",
                ["r"] = "RenumberMarkersInOrder",
            }},

            ["e"] = {"+envelopes", {
                ["a"] = "ToggleArmEnvelope",
                ["b"] = "ToggleEnvelopeBypass",
                ["A"] = "ToggleArmAllEnvelopes",
                ["A"] = "UnarmAllEnvelopes",
                ["d"] = "ClearEnvelope",
                ["D"] = "ClearAllEnvelopes",
                ["v"] = "ToggleVolumeEnvelope",
                ["p"] = "TogglePanEnvelope",
                ["t"]  = "ToggleShowAllEnvelopes",
                ["T"] = "ToggleShowSelectedEnvelope",
                ["w"] = "SelectWidthEnvelope",
                ["y"] = "CopyEnvelope",
                ["s"] = {"+shape", {
                    ["b"] = "SetEnvelopeShapeBezier",
                    ["e"] = "SetEnvelopeShapeFastEnd",
                    ["f"] = "SetEnvelopeShapeFastStart",
                    ["l"] = "SetEnvelopeShapeLinear",
                    ["s"] = "SetEnvelopeShapeSlowStart",
                    ["S"] = "SetEnvelopeShapeSquare",
                }},
            }},

            ["f"] = { "+fx", {
                ["a"] = "AddFx",
                ["d"] = "CutFxChain",
                ["f"] = "ToggleShowFxChain",
                ["y"] = "CopyFxChain",
                ["p"] = "PasteFxChain",
                ["b"] = "ToggleFxBypass",
                ["i"] = {"+input", {
                         ["s"] = "ToggleShowInputFxChain",
                         ["d"] = "CutInputFxChain",
                }},
                ["s"] = {"+show", {
                         ["1"] = "ToggleShowFx1",
                         ["2"] = "ToggleShowFx2",
                         ["3"] = "ToggleShowFx3",
                         ["4"] = "ToggleShowFx4",
                         ["5"] = "ToggleShowFx5",
                         ["6"] = "ToggleShowFx6",
                         ["7"] = "ToggleShowFx7",
                         ["8"] = "ToggleShowFx8"
                }},
            }},

            ["t"] = { "+track", {
                ["R"] = "RenderTrack",
                ["r"] = "RenameTrack",
                ["z"] = "MinimizeTracks",
                ["m"] = "CycleRecordMonitor",
                ["f"] = "CycleFolderState",
                ["i"] = "SetTrackInputToMatchFirstSelected",
                ["y"] = "SaveTrackAsTemplate",
                ["i"] = {"+insert", {
                         ["c"] = "InsertClickTrack",
                         ["t"] = "InsertTrackFromTemplate",
                         ["v"] = "InsertVirtualInstrumentTrack",
                         ["1"] = "InsertTrackFromTemplateSlot1",
                         ["2"] = "InsertTrackFromTemplateSlot2",
                         ["3"] = "InsertTrackFromTemplateSlot3",
                         ["4"] = "InsertTrackFromTemplateSlot4",
                }},
                ["s"] = {"+sends", {
                        ["m"] = "MuteAllSendsFromTrack",
                }},
                ["x"] = {"+routing", {
                        ["p"] = "TrackToggleSendToParent",
                        ["s"] = "ToggleShowTrackRouting",
                }},
                ["F"] = { "+freeze", {
                        ["f"] = "FreezeTrack",
                        ["u"] = "UnfreezeTrack",
                        ["s"] = "ShowTrackFreezeDetails",
                }},
            }},
        }},
    }
}
